/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BicycleRentalApplication;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Akihiko Shuji
 */
public class AccountInformation_Edit extends javax.swing.JFrame {

    /**
     * Creates new form AccountInformation_Edit
     */
    
    public int CurrentUser;

    public AccountInformation_Edit() {
        initComponents();
        FName.setText(User.Users.get(CurrentUser).getfName());
        LName.setText(User.Users.get(CurrentUser).getlName());
        Email.setText(User.Users.get(CurrentUser).getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Email = new javax.swing.JTextField();
        LName = new javax.swing.JTextField();
        FName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Interface = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        SaveChanges = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(440, 890));
        setPreferredSize(new java.awt.Dimension(440, 890));
        setSize(new java.awt.Dimension(440, 890));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(440, 890));
        jPanel1.setPreferredSize(new java.awt.Dimension(440, 890));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(204, 204, 204));
        Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailFocusGained(evt);
            }
        });
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 270, 40));

        LName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LName.setForeground(new java.awt.Color(204, 204, 204));
        LName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LNameFocusGained(evt);
            }
        });
        LName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNameActionPerformed(evt);
            }
        });
        jPanel1.add(LName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 270, 40));

        FName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FName.setForeground(new java.awt.Color(204, 204, 204));
        FName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FNameFocusGained(evt);
            }
        });
        FName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNameActionPerformed(evt);
            }
        });
        jPanel1.add(FName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 270, 40));

        jPanel2.setBackground(new java.awt.Color(246, 246, 246));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 280, 60));

        jPanel3.setBackground(new java.awt.Color(246, 246, 246));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, -1, -1));

        Interface.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfacesImage/Account Information_Edit.png"))); // NOI18N
        jPanel1.add(Interface, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 430, 910));

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 40));

        SaveChanges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveChangesMouseClicked(evt);
            }
        });
        jPanel1.add(SaveChanges, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 710, 220, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        
        try {
            new AccountInformation().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(AccountInformation.class.getName()).log(Level.SEVERE, null, ex);
        } //End of try/catch
        this.dispose();
        
    }//GEN-LAST:event_backMouseClicked

    private void LNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNameActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void FNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNameActionPerformed

    private void SaveChangesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveChangesMouseClicked
        
        if(FName.getText().isEmpty())
            User.Users.get(CurrentUser).setfName(FName.getText());
        if(LName.getText().isEmpty())
            User.Users.get(CurrentUser).setlName(LName.getText());
        if(Email.getText().isEmpty())
            User.Users.get(CurrentUser).setEmail(Email.getText());
        
        new AccountInformayion_EditSuccessful().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_SaveChangesMouseClicked

    private void FNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FNameFocusGained
        
        FName.setText("");
        FName.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_FNameFocusGained

    private void LNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LNameFocusGained
        
        LName.setText("");
        LName.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_LNameFocusGained

    private void EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFocusGained
        
        Email.setText("");
        Email.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_EmailFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountInformation_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountInformation_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountInformation_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountInformation_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountInformation_Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FName;
    private javax.swing.JLabel Interface;
    private javax.swing.JTextField LName;
    private javax.swing.JLabel SaveChanges;
    private javax.swing.JLabel back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
