/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BicycleRentalApplication;

import java.util.logging.Level;
import java.util.logging.Logger;

public class HomePage extends javax.swing.JFrame {

    public int CurrentUser;

    public HomePage() {
        initComponents();
        UserName.setText(User.Users.get(CurrentUser).getfName() + " " + User.Users.get(CurrentUser).getlName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UserName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Interface = new javax.swing.JLabel();
        SignOut = new javax.swing.JLabel();
        RentBicycle = new javax.swing.JLabel();
        AccInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserName.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        UserName.setForeground(new java.awt.Color(5, 63, 94));
        UserName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        UserName.setText("           ");
        jPanel1.add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 210, 210, 30));

        jPanel3.setBackground(new java.awt.Color(5, 63, 94));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 50));

        jPanel2.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 190, 40));

        Interface.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfacesImage/Home page.png"))); // NOI18N
        jPanel1.add(Interface, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 430, 920));

        SignOut.setText("         ");
        SignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignOutMouseClicked(evt);
            }
        });
        jPanel1.add(SignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 90, -1));

        RentBicycle.setText("                  ");
        RentBicycle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RentBicycleMouseClicked(evt);
            }
        });
        jPanel1.add(RentBicycle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 160, 160));

        AccInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccInfoMouseClicked(evt);
            }
        });
        jPanel1.add(AccInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 160, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignOutMouseClicked
        
        new startPage().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_SignOutMouseClicked

    private void RentBicycleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RentBicycleMouseClicked

        new RentBicycle().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_RentBicycleMouseClicked

    private void AccInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccInfoMouseClicked
        
        new AccountInformation().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_AccInfoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccInfo;
    private javax.swing.JLabel Interface;
    private javax.swing.JLabel RentBicycle;
    private javax.swing.JLabel SignOut;
    private javax.swing.JLabel UserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
